GET http://localhost:8080/hello

###
GET http://localhost:8080/staff?id=s02

###

GET http://localhost:8080/hello/exception

###

###
GET http://localhost:8080/hello/dateFormat?date=2020-01-02&name=   df dfdf

###

GET http://localhost:8080/hello/model?name=343

###
GET http://localhost:8080/actuator/env


###